# Setup
title:               'greggorievich''s house of confusion'
tagline:             'Tech Meets Redneck'
description:         'Documenting whatever I feel like since I published the site.'
url:                 https://greggorievich.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              greggorievich
  url:               https://greggorievich.github.io/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
excerpt_separator: "<!--excerpt-->"